name: Check Lint

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
            - run: npm ci
            - run: npm run check-lint
